name: Windows/aarch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-11-arm
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout JDK repository
        uses: actions/checkout@v4

      - name: Remove current JRE
        run: |
          git rm -rf win/aarch64 || true

      - name: Adjust JRE
        run: |
          $JAVA_HOME_25_arm64/bin/jlink  --module-path $JAVA_HOME_25_arm64/jmods --add-modules java.base,java.desktop,java.logging,java.naming,java.transaction.xa,java.rmi,java.management,java.security.jgss,java.sql,jdk.crypto.ec,jdk.httpserver,java.compiler --output ./win/aarch64 --no-header-files  --no-man-pages  --strip-debug  --compress=2
          rm -rf ./win/aarch64/bin/*exe

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "win_aarch64: update JRE"
          title: "Automated update for Windows/aarch64"
          body: "This PR was automatically generated by a GitHub Action."
          branch: update_win_aarch64
          base: master
